In [1]:
!pip install git+https://github.com/YingfanWang/PaCMAP/

  Cloning https://github.com/YingfanWang/PaCMAP/ to /tmp/pip-req-build-nqu9uun0
  Running command git clone -q https://github.com/YingfanWang/PaCMAP/ /tmp/pip-req-build-nqu9uun0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done


In [2]:
import pacmap
import numpy as np

/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)


In [3]:
from sklearn import datasets


In [4]:
iris = datasets.load_iris()['data']

In [5]:
iris[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
m = pacmap.PaCMAP( save_tree=True)

In [7]:
xhat = m.fit_transform(iris)
xhat[:5,:]

array([[-13.382138 ,   7.4899983],
       [-15.308793 ,   5.2775564],
       [-16.02687  ,   5.4398007],
       [-16.010708 ,   5.3732424],
       [-13.44133  ,   8.113907 ]], dtype=float32)

In [8]:
xhat2 = m.transform(iris, None) #save_tree was true so should not need basis?
xhat2[:5,:]

TypeError: ignored

In [9]:
xhat3 = m.transform(iris, basis=iris.astype(np.float32)) #provide iris
xhat3[:5,:]

array([[-16.141    ,   5.4488974],
       [-16.141    ,   5.448899 ],
       [-16.141    ,   5.4488983],
       [-16.141    ,   5.4488974],
       [-16.141    ,   5.4488983]], dtype=float32)

In [10]:
xhat4 = m.transform(iris, basis=xhat) #provide predictions
xhat4[:5,:]

array([[-16.141    ,   5.4488974],
       [-16.141    ,   5.448899 ],
       [-16.141    ,   5.4488983],
       [-16.141    ,   5.4488974],
       [-16.141    ,   5.4488983]], dtype=float32)

# save_tree = False

In [18]:
m2 = pacmap.PaCMAP( save_tree=False)

In [19]:
xhat = m2.fit_transform(iris)
xhat[:5,:]

array([[-17.559126 ,   1.7458816],
       [-17.634377 ,  -0.6560277],
       [-18.294754 ,  -1.1788979],
       [-18.396496 ,  -1.5074022],
       [-18.311749 ,   2.3693123]], dtype=float32)

In [20]:
xhat2 = m2.transform(iris, None) #save_tree was false so should error?
xhat2[:5,:]

AssertionError: ignored

In [22]:
xhat3 = m2.transform(iris, basis=iris.astype(np.float32)) 
xhat3[:5,:]

array([[-17.953388  ,   1.8956025 ],
       [-17.76003   ,  -0.53079784],
       [-18.188265  ,  -1.0616949 ],
       [-18.28627   ,  -1.2768    ],
       [-18.10463   ,   2.1892297 ]], dtype=float32)

In [15]:
xhat4 = m2.transform(iris, basis=xhat)
xhat4[:5,:]

ValueError: ignored

In [23]:
xhat5 = m2.transform(iris[:5,:], basis=iris.astype(np.float32)) 
xhat5[:5,:]

array([[-17.953388  ,   1.8956025 ],
       [-17.76003   ,  -0.53079784],
       [-18.188265  ,  -1.0616949 ],
       [-18.28627   ,  -1.2768    ],
       [-18.10463   ,   2.1892297 ]], dtype=float32)